import 'package:get/get.dart';

List<Testimony> engTestimony = [
  Testimony(
    data:
        "I am really indebted for being the part of Santi with the instrumental role. It is great to share my feeling about working from day 1 here. Santi has been a platform for the employees, the job-seekers and the foreign clients to exercise their potential to the career and the business goal as well. It is truly a one stop business solution partner as we deal with every foreign employment related issues through fast track. I don’t hesitate to state that Santi is scaling the apex in recruiting the workers for multinational companies as we are practicing RBA.In the nutshell, Santi Overseas Pvt. Ltd. has been the best choice of those individuals who are seeking jobs in foreign countries, and of those foreign clients who want to hire the elegant workforce to meet the business goal. The team is committed to give the best services through the veterans. Thank you!",
    name: "Surendra Rana",
  ),
  Testimony(
    data:
        "Ladies and Gentlemen !Let me share my sheer joy to be a part of this global forum of RBA via Santi Overseas Pvt. Ltd. Working with the team of veterans in the field of foreign employment has molded me much more in my performance. I am very privileged as the Program Co-ordinator, and striving for 100% to place Santi at the top among those who have had their own glorious history in this supply chain. Since we are a service oriented ethical agency, our primary focus goes on recruitment and deployment of an elegant work force to the employing company. We are truly committed to comply with the RBA COC  and the accessories during the total ethical practice. Ladies and gentlemen, ethically fair or transparent business is our commitment through the compliance of all the aspects of RBA Code of Conducts. We are proud of being involved, a brick of an esteemed castle, hoping to make this forum as the landmark. Hence, I would like to request all the members to unite for the promotion of all manufacturing and service  sectors holistically. Thank you !    ",
    name: "Rishi Ram Kapri",
  ),
  Testimony(
      data:
          "Dear valued clients,\nGreetings!\nWe take immense pleasure in introducing SANTI OVERSEAS PVT. LTD. as an ethical Human Resource recruitment agency based in the capital city of Nepal, Kathmandu. We are duly licensed by the Government of Nepal under the Department of Foreign Employment act with License No. 1495/074/075.\nGlobalization has made many things possible to have easy access to different resources from every nook and corner of this dynamic world. Moreover, forming a common platform with a global supply chain of goods and services has assisted the companies to accelerate the pace to meet the business goal. And, it is true to say that human resource is one of the strongest pillars for the sustainable growth of business. However, it has become the most critical decision a company has to make since it can be messed up. Keeping this in mind,  we lay great emphasis on the quality, attitude and skills of the personnel we offer to our clients ensuring timely, sound and cost-effective staffing.\nWe do assist our clients’ understanding in developing and implementing effective human resource recruiting and supplying programs and policies by working closely with them addressing their most important HR issues. We can source our clients with a wide range of personnel especially in the field of Industry, Security, Hospitality, Agriculture, Plantation, Sales & Marketing, Engineering, Construction, Corporate and IT sectors.\nThe company has aimed to give a complete HR solutions & support service to our valued clients to take the fullest advantage of our professional services that we offer. We have been closely associated with the development in our every endeavor to fulfill the employers’ as well as employees’ interests with our main concern for their full satisfaction.\nOur clients’ enquiry about HR solutions shall be nourished with the greatest care and we fully assure that our experienced team which is professionally trained and have already sourced a vast range of workforce to Malaysia and many other countries in the Middle East is committed in providing with the best quality services all the times.\nFinally, we are glad to be the part of an esteemed global forum, Responsible Business Alliance, and are committed to comply with the Code of Conduct hoping for a long-term mutually beneficial relationship in business. Thank you!",
      name: "Desk of the Chairman"),
  Testimony(
      data:
          "Mr. Manu Kumar Lama is an accomplished and self-driven professional with an entrepreneurial unmatched spirit. Having a rich experience in the human resource management industry both in Nepal and Malaysia, Mr. Lama carries the overall responsibilities for the recruitment policies. For his excellent managerial skills and  knowledge, he strives for highly potential candidates nurturing them ethically to instill enthusiasm. The feedback from the thousands of candidates deployed to Malaysia, UAE, Saudi Arabia, Qatar and Oman along with the employers have proved his leadership and professionalism  in this business. The quality of dealing with the difficulties tactfully and critically has led him to the apex to build up a huge network in this field. His outstanding knowledge on Malay language both written and spoken has added a great asset in him establishing the relation of brotherhood among many big companies and people as well.\nMr. Manu Kumar Lama, being the member of different social organizations, has been involved in many social welfare and volunteer activities. His charitable attribute is reflected in the companies he is involved advocating different facilities to the staffs and those who go for foreign employment. He has played an instrumental role in SANTI to guild the business with ZERO COST policy to address the G2G agreement held between the Malaysian government and the government of Nepal, and in accordance with the RBA Code of Conduct. The Board of Directors are  proud of  the veteran Mr. MK Lama, the founder member and the Managing Director, wishing him all the best for his further success in this realm.",
      name: "MANAGING DIRECTOR")
];

List<Testimony> nepTestimony = [
  Testimony(
    data:
        "सान्तिको भूमिकामा भूमिका निर्वाह गरेकोमा म साँच्चै ऋणी छु। यहाँ दिन 1 देखि काम गर्ने बारे मेरो भावना साझा गर्न राम्रो छ। Santi कर्मचारी, जागिर खोज्ने र विदेशी ग्राहकहरु लाई आफ्नो करियर र व्यापार लक्ष्य को लागी आफ्नो क्षमता प्रयोग गर्न को लागी एक प्लेटफर्म भएको छ। यो साँच्चै एक स्टप व्यापार समाधान साझेदार हो किनकि हामी फास्ट ट्र्याक मार्फत हरेक वैदेशिक रोजगारी सम्बन्धी मुद्दाहरू समाधान गर्छौं। म यो बताउन हिचकिचाउँदिन कि सन्तीले बहुराष्ट्रिय कम्पनीका लागि कामदार भर्ती गर्न शीर्ष मापन गरिरहेको छ किनकि हामी आरबीए अभ्यास गरिरहेका छौं। संक्षेपमा, Santi Overseas Pvt. Ltd. विदेशी देशहरूमा रोजगारी खोजिरहेका व्यक्तिहरू र व्यापार लक्ष्य पूरा गर्न सुरुचिपूर्ण कार्यबललाई भर्ती गर्न चाहने विदेशी ग्राहकहरूका लागि उत्तम छनोट भएको छ। टोली दिग्गजहरू मार्फत उत्कृष्ट सेवाहरू दिन प्रतिबद्ध छ। धन्यवाद!",
    name: "सुरेन्द्र राणा",
  ),
  Testimony(
    data:
        "महिला तथा सज्जनबृन्द, शान्ति ओभरसिज प्रा.लि को माध्यमबाट RBA को यो ग्लोबल मन्चको एउटा सदस्य हुन पाएकोमा म यहाँहरु समक्ष मेरो गहिरो खुशि बाडन चाहन्छु l बैदेशिक रोजगार संग सम्वन्धित अनुभवी र दक्ष व्यक्ति हरुको समुहमा काम गर्दा म आफू पनि परिष्कृत हुदै कार्यक्रम संयोजकको रुपमा यस संस्थालाई एक गौरवशाली इतिहास कायम राख्दै बैदेशिक रोजगारीको क्षेत्रमा एक अग्रणी संस्थाको रुपमा स्थापित गर्न हरसम्भव प्रयासरत रहिअएका छौं l शान्ति ओभरसिज प्रा.लि. RBA को आचार संहिता भित्र रहेर बैदेशिक रोजगारीमा जान चाहने नेपाली युवाहरुलाई सम्पूर्ण रुपले शुन्य लागतमा प्रशिक्षण प्रदान गरी उनीहरुको दक्षता र सीप अनुसारको रोजगारी प्राप्त गर्न यस संस्थाको सम्पर्कमा रहेका विभिन्न देशका बहुराष्ट्रिय कम्पनीहरुमा आकर्षक सेवा सुविधाका साथ पठाउने एक सेवाप्रदायक सदस्य सस्था हो  l शुन्य लागत अन्तर्गत बैदेशिक रोजगारीमा जान चाहने प्रशिक्षार्थी कामदारहरुको पासपोर्ट बनाउने, घरदेखि काठमाडौ सम्म जाने यातायात खर्च, खाने बस्ने खर्च, फोटो खिच्ने र मेडिकल चेकअप खर्च, भिषा फी र हवाई टिकट, एयरपोर्ट सम्म जाने र अर्को देशको  एयरपोर्टमा पुगेपछि लिन आउने र होस्टेल सम्म पुर्याउने सम्मका सम्पूर्ण खर्च पर्दछ अर्थात्   प्रशिक्षार्थी कामदारहरुले यी माथि उल्लेखित कुनैपनि खर्च तिर्नुपर्ने छैन l तसर्थ: शान्ति ओभरसिज को तर्फबाट बैदेशिक रोजगारीमा जान चाहने सम्पूर्ण युवाहरुलाई  बैदेशिक रोजगारी सम्वन्धी कुनै समस्या तथा जिज्ञासा रहेमा कुनै एजेन्ट बिनानै हामीलाई सम्पर्क गर्नुहुन अनुरोध गर्दछौ l एजेन्टहरुको लहैलहैमा लागेर  आफ्नो पैसा नफसाउनु हुन पनि हामी सचेत गराउदछौ l  ",
    name: "ऋषिराम काप्री",
  ),
  Testimony(
      data:
          "यहाँहरु सबैमा नमस्कार, नेपाल सरकारको वैदेशिक रोजगार विभागबाट लाइसेन्स नम्बर १४९५/०७४/०७५ प्राप्त काठमाडौं महानगरपालिका वडा न. ४, महाराजगन्ज चुनदेवीमा अवस्थित शान्ति ओभरसिज प्रा.लि को अध्यक्ष को तर्फबाट यहाँहरु सबैलाई नमस्कार गर्दै यस संस्थामा स्वागत गर्न चाहन्छु l  \nभूमण्डलीकरणले गतिशील आजको विश्वको कुना कन्दरामा पनि मानिसको पहुचलाई सजिलो बनाएको आजको अवस्थामा विश्वको विभिन्न ठाउँमा उपलब्ध बस्तु तथा सेवा वितरणलाई पनि फराकिलो बनाएको कुरा सबैमा विदितै छ l यहि कुरालाई मध्यनजर गर्दै नेपाल सरकारले सम्झौता गरे अनुरुपका देशहरुका ठूला र बहुराष्ट्रिय उत्पादनमुलक कम्पनीहरुलाई आवश्यक पर्ने मानव संसाधन प्रचलित कानूनको बर्खिलाप नहुने र सम्पूर्णरुपले कानूनी मापदण्ड पूरागरी पूर्ति गर्ने उद्देश्यका साथ शान्ति ओभरसिज प्रा.लि. ले RBA जस्तो अन्तर्राष्ट्रिय मंचको सदस्यता लिएर शुन्य लागतमा सम्पूर्णरूपले जाने देश, कम्पनी, कामको प्रकृति र सेवा सुविधा आदिको बारेमा प्रशिक्षण दिई इच्छुक व्यक्तिहरुलाई बैदेशिक रोजगारीमा पठाउदछ l \nयसरी वैदेशिक रोजगारीका लागि पठाउने कामदारहरुको छनौट गर्दा शान्ति ओभरसिज प्रा.लि. ले जहिले पनि रोजगारदाता कम्पनीहरुले तोकेको मापदण्डलाई प्राथमिकतामा राख्दै ………… ",
      name: "Desk of the Chairman"),
  Testimony(
      data:
          " यस शान्ति ओभरसिज प्रा.लि. का प्रबन्ध निर्देशक श्री मनु कुमार लामा बैदेशिक रोजगारीको क्षेत्रमा एक सु-परिचित नाम हो l विशेषत: नेपाल र मलेशियाका सरकारहरुको बिचमा भएको श्रम सम्झौता सम्बन्धि जानकार र मलाया भाषाका विज्ञ हुनुले पनि मलेशियाका दर्जनौ ठूला बहुराष्ट्रिय कम्पनीहरु संगको बर्षौ देखिको उहाँको सहकार्य आफैमा एक गौरवशाली सफलता बनेको छ l यस्तो परिप्रेक्षमा उहाँले नेतृत्व प्रदान गर्नुभएको यस शान्ति ओभरसिज प्रा.लि. आज बैदेशिक रोजगारीको क्षेत्रमा एक अग्रणी संस्थाको रुपमा स्थापित भएको कुरा सबैमा विदितै छ l ",
      name: "MANAGING DIRECTOR'S")
];
List<String> testimonialImage = ["assets/Surendra.jpg","assets/RishiRam.jpg","assets/Chairman.jpg","assets/Director.jpg"];

class Testimony {
  String name;
  String data;
  Testimony({required this.data, required this.name});
}
