import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_EN': {
          'job': 'Jobs',
          'companies': 'Companies',
          'aboutUs': 'About Us',
          'login/signup': 'Login/SignUp',
          'forEmployees': 'For Employees',
          'Find the best work at foreign employment through SANTI OVERSEAS.':
              'Find the best work at foreign employment through SANTI OVERSEAS.',
          'Fill up your profile to get your dream job.':
              'Fill up your profile to get your dream job.',
          'santiOverseas': 'SANTI\nOVERSEAS',
          'New Job': "New Jobs",
          'News': 'News',
          'FAQs': 'FAQs',
          'Testimonials': 'TESTIMONIALS',
          'companyInfo': "Company Info",
          'companyInfo1':
              "➼  Santi Overseas Pvt. Ltd, established under the Company Act 2053 of Nepal Government with Registration No. 176847/074/075, and Department of Foreign Employment. Government of Nepal with License No. 1495/074/075, is one of the leading manpower recruitment agencies in Nepal operated by a team of experts in the field of recruitment services. Within the short period of time, the company has gained vast experience enabling it to be one of the reputed companies in the country, and it has owned remarkable achievement  ensuring the total satisfaction of many renewed companies and organizations inside the country and overseas as well.\n\n➼  Santi Overseas Pvt. Ltd. has dispatched many professionals (skilled, semi- skilled and unskilled) from Nepal to Malaysia. (UAE, Qatar, Kuwait, Oman, Bahrain, Saudi Arabia and many more countries.) The highly qualified professionalism of the company makes the clients get maximum output at minimum cost and effort. Since we have never failed our clients in the past and will make it equally easy for them in future, they can fully rely on us.  We compete in the employment service industry by offering a complete range of recruitment services with in the framework of the business ethics.\n\n➼  The reason why Santi Overseas has retained some of its clients gained at the beginning of its operations is the philosphy to view its manpower as a partnership and a bridge to build a lasting relationship with them. At the core, Santi Overseas's philosophy is its commitment to provide Top Quality Recruitment Solutions. We always aim to exceed client's expectations as we view every recruitment undertaking as a long-term partnership born out of trust, competency and service satisfaction. Many of our existing clients have enjoyed the benefits of our professionalism and integrity which has enabled us to search and sign up top-quality workers from some of the world's well-known and established companies and industries, and career of candidates we have considered and deployed.",
          'vision': 'VISION',
          'vision1':
              '➼  To be the best worldwide provider of high-value staffing services and the center for quality employment opportunities. ',
          'mission': 'MISSION',
          'mission1':
              '➼  To provide distinctive services to our clients and maintain legal practices.',
          'mission2':
              '➼  To meet the expectation of our clients and applicants through optimum utilization of our available manpower resources. ',
          'mission3':
              '➼  To be a benchmark model in the application of quality management in the manpower industry in Nepal.',
          'focus': 'FOCUS',
          'focus1':
              '➼  To provide a highly resourceful and dynamic exchange between opportunity seekers and employers.',
          'focus2':
              "➼  To provide the World's most complete End-to-End solution to our clients through well-defined systems, process and strategic initiatives.",
          'focus3':
              '➼  To provide best possible support in searching the right kind of   candidates by strictly adhering to the policy.',
          'focus4':
              '➼  To cover entirely the leading sectors like Engineering, Maintenance, Constructions, Manufacturing, Service, Security, Hospitality etc.',
          'focus5':
              '➼  To support the empowerment of overseas workers through educational awareness and direct involvement.',
              'cooperate':'CORPORATE VALUES',
              'cooperate1':'To demonstrate our steadfast commitment to: ',
              'cooperate2':'Leadership: We will be a leader in every aspect of our business and in development of our team. Leadership skills in our performance is the way we manage, design, build and support our products. ',
              'cooperate3': 'Customer satisfaction: Our success depends upon the satisfaction of our    customers, and that is to be achieved through the total understanding of what they actually want, and delivering it flawlessly. ',
              'cooperate4': 'Integrity: We practice the highest ethical standards by honoring our commitments. ',
              'cooperate5': 'Quality: We strive for continuous quality    improvement in all that we do. ',
            'recruit': 'WHY  TO RECRUIT NEPALESE WORKERS?',
            'recruit1': 'Through the experience gained over the year in the foreign employment, it has been seen that many countries have shown their interest in hiring the Nepalese professional, skilled, semi-skilled and unskilled manpower because of the following reasons :',
            'recruit2': '➼ We are always between clients and candidates to assure that recruitment process runs quickly and smoothly and inform them about the progress in every step',
            'recruit3': '➼ We have developed a web and mobile app to facilitate the enrollment of nepali worker. ',
            'recruit4': '➼ We help you to get the best candidates and best jobs. ',
            'recruit5': '➼ We provide services through our team of highly professional and trained recruitment consultants. ',
            'recruit6': '➼ We are very cost effective without compromising with the quality. ',
            'recruit7': '➼ We focus on individual approach to our clients and candidates to understand their requirements and special needs to achieve quality results.',
            'recruit8': '➼ We are known for deployment of quality and reliable manpower on time according to employer\'s convenience ',
            'recruit9': '➼ We are responsive as well as communicative, so we do not let any gaps in between the client and us. We are transparent and make the recruitment process as simple as possible.',
            'recruit10': '➼ We are affiliated with top Training Institute and we can provide refreshment training and full training as well to the applicant whenever they require. ',
            'terms':'RECRUITMENT TERMS AND CONDITIONS',
            'terms1':'1. The FIRST PARTY shall issue the Demand letter to the SECOND PARTY mentioning the number of workers required and their categories, rate of salary and other service conditions of workers, along with Power of Attorney, Guarantee Letter, Manpower Recruitment Agreement and Employment Contract (authorizing the SECOND PARTY) to recruit and expatriate the worker from Nepal on behalf of the FIRST PARTY. Demand Letter and Power of Attorney should be attested by the Chambers of Commerce of employing country, Foreign Ministry and Nepal Embassy. ',
            'terms2':'2. Both parties herein shall obtain the approval of the respective government to import, recruit and supply the workers as per the rules and regulation of both countries in regard to the condition necessary to import and supply. ',
            'terms3':'3. The SECOND PARTY shall be responsible for short-listing of qualified candidates according to their trade qualifications and experience in conformity with the FIRST PARTY\'S requirements. The SECOND PARTY should notify the FIRST PARTY of such short listed qualified candidates who are ready for final Interview and selection. ',
            'terms4':'4. The FIRST PARTY has the right to either send his representative or give the SECOND PARTY the right to select process and send such qualified workers at the SECOND PARTY\'S full guarantee. ',
            'terms5':'5. The worker will be interviewed, tested and selected by representative of the employer or by SECOND PARTY on his behalf. The FIRST PARTY agrees to advise to the SECOND PARTY of its final list personnel selected through fax, email or letter and the desired mobilization date on the respective site. ',
            'terms6':'6. The SECOND PARTY shall assist the workers in matters related to Nepal immigration and government formalities, medical tests and Visa stamping along with all other relevant approvals from the embassy of the country concerned. ',
            'terms7':'7. The SECOND PARTY shall, at his own expenses, provide airport assistance to the departing workers and inform the FIRST PARTY of their arrival detail by any means of communication (Fax, Email or Telephone) so as to receive them on arrival. ',
            'terms8':'8. The FIRST PARTY will pay all the expenses to bring the candidates to Malaysia. ',
            'terms9':'9. The FIRST PARTY will be responsible for receiving the workers at the airport in part and as whole as per requirement of the client and validity of Visa of the concerned country. ',
            'terms10':'10. The earning of the worker per month and other service conditions shall be as per the attached demand letter and contract document against each category. The FIRST PARTY should clearly inform the SECOND PARTY about the salary and any other deduction as Tax etc being paid by the employer and SECOND PARTY in turn should clearly inform the candidate accordingly. ',
            'terms11': '11. Within the three (3) month probation period from the commencement of employment, if the employer finds the selected worker to be unfit, unqualified to continue the employment, refuse to work, failed the medical tests upon arrival to destination country or considered as a security threat, the EMPLOYER may replace the worker. The replacement of the unqualified worker shall be done by the SECOND PARTY at maximum of a month from the termination of the unqualified worker. All expenses incurred, in relation there to, shall be borne by the SECOND PARTY. ',
            'terms12': '12. Arrival of the selected candidates will be within One Month upon issuing their visas. For any delay rather than this period, the visas will be cancelled and the SECOND PARTY will shoulder all the governmental expenses for replacement. ',
            'terms13': '13. FIRST PARTY has to compensate the candidate on their own expenditure if  the candidate will not get all facilities as per Employment Contract, and the  company will collapse before contract periods. ',
            'terms14': '14. The FIRST PARTY agrees to bear the compensation in case of death or injury of the workers and also agrees to bear the cost of transport of dead body to Nepal as per the labor law of country concerned. ',
              'recuitment': 'RECRUITMENT PROCEDURES',
              'recuitment1': '1. Initial Enquiry from employer: ',
              'recuitment2': 'The employer may contact recruitment companies directly and discuss your specific requirement and details on terms and conditions of service for Nepali workers. ',
              'recuitment3': '2. Legal Documents from employer for government formalities. ',
              'recuitment4': 'Once requirement is confirmed and initial agreement is made between recruitment companies (Nepal) and employer regarding terms and conditions and selection process, the employing company requires to produce the following duly authenticated/ attested documents in favor of recruitment companies (Nepal) to finalize the recruiting process as per Nepalese Government labor law: ',
              'recuitment5': '1. Power of Attorney between Recruiting Agent and Employer. ',
              'recuitment6': '2. Demand Letter listing the manpower requirement and terms and conditions. ',
              'recuitment7': '3. Employment Contract including terms and conditions of service. ',
              'recuitment8': '4. Recruitment Service Agreement listing each party responsibility. ',
              'recuitment9': '5. Guarantee letter confirming country of employment. ',
              'recuitment10': 'Once the above mentioned original documents are received from employer, recruitment companies will submit application to Department of Labor for authorization. ',
              'recuitment11': '2. Pre-Labour Approval: ',
              'recuitment12': 'After receiving the authorized demand letter from the company, the document are presented for pre- labor approval. The department of Labor in Nepal analyzes the document and approve for further processing. ',
              'recuitment13': '3. Manpower Pooling: Advertisement, Screening and short listing. ',
              'recuitment14': 'Once the Department of Labor is satisfied about the credibility of the demand, attestation and terms and conditions offered are conformity with the government regulation, the Government grants the permission to recruiting agency for advertise the requirement in local and national newspapers and start of recruitment process. Recruitment Company starts screening and short listing candidates before final interview. The process includes: ',
              'recuitment15': '1. Print and Broadcast Media Advertisement ',
              'recuitment16': '2. On-the-spot-sourcing (City and Provincial) ',
              'recuitment17': '3. Through Our Highly Qualified Agents ',
              'recuitment18': '4. Recommended Personnel ',
              'recuitment19': '5. Internal Candidate Bank ',
              'recuitment20': '4. Selection: ',
              'recuitment21': 'The mode of selection of contract workers may be executed under the following procedures: ',
              'recuitment22': 'Preliminary Interview: ',
              'recuitment23': 'We maintain upto date data bank of potential candidates with full information on their skill and education, technical knowhow and experience as per the employer criterion. Santi Overseas will short list the candidate for pre-interview and determine the capabilities of each applicant via one-on-one interviews to ascertain who are most qualified and fit for the employer\'s final selection. ',
              'recuitment24': 'Final Interview/Selection: ',
              'recuitment25': 'Selection by Employer\'s Authorized Representative, Recruitment Company Personnel. ',
              'recuitment26': 'Direct Interview (by Employer): ',
              'recuitment27': '  Many employers visit Nepal for final interview. We make all necessary preparations for interview. We call short listed candidates for the particular day. ',
              'recuitment28': 'Interview on behalf of Employer: ',
              'recuitment29': 'Sometimes manpower importing agencies give full authority to manpower consultant for entire selection procedures. In such case, we carry out interviews on behalf of employers abroad and make all dispatching arrangements to the employment destination. The selection is made purely on merit basis and finally select the most competent workers from our manpower reserve. ',
              'recuitment30': 'Interview through Skype: ',
              'recuitment31': 'Sometimes manpower importing agencies  select the candidate through interview via online (Skype). We make all the necessary arrangements for this process. ',
              'recuitment32': 'Transmittal of Resumes: ',
              'recuitment33': 'Employer may select the candidates from the Resumé of all prospective candidates. We forward the resumés of the candidates who have passed the pre-qualification interview and testing conducted at our end. In such cases, the name of the successful candidates may be relayed to us via phone, fax, or email. ',
              'recuitment34': '5. Full Documentation Assistance: ',
              'recuitment35': 'We provide the selected applicants\' assistance in securing the travel documents required by both Labour Office and Embassy, like Trade Test, Passport, Police Clearance, Medical Certificate, Orientation and Exit Pass. ',
              'recuitment36': '6. Medical Checkup: ',
              'recuitment37': 'The selected candidates are sent to an authorized hospitals or clinics for a full medical examination (and vaccination if required). The candidates who are medically and physically fit for employment are forwarded for recruitment process such as contract signing, visa processing. ',
              'recuitment38': '7. Employment Visa Process: ',
              'recuitment39': 'Once selected candidates are medically and physically fit, employer has to process their employment visa. The Visa system varies country to country. For the country with paper visa system, employer has to make copy of issued visa available to recruitment companies as soon as visa is issued for individuals for government clearance for mobilization. But for the country where visa has to be endorsed onto a passport, employing company provides all necessary documents to assist visa endorsement from embassy of employing country. ',
              'recuitment40': '8. Orientation: ',
              'recuitment41': 'Nepal labor law requires all new candidates traveling overseas for employment take orientation class to familiarize local laws & orders, labor laws and immigration policy, environment and tradition and culture of employing country. Candidates should also understand their responsibilities, terms and conditions and benefits of employment prior to submitting for final approval for mobilization. ',
              'recuitment42': '9. Final Labour Approval: (Government Clearance) ',
              'recuitment43': 'All the necessary documents like original passport, visa copy (original if not issued online), medical report, orientation certificate, insurance policy are submitted in Labor Department of Nepal for final approval and immigration clearance. The Department of Labor analyzes the documents and provides final approval. ',
              'recuitment44': '11. Travel Arrangement: ',
              'recuitment45': 'Once paper visa is received or visa is endorsed from embassy of employing country, Employer may proceed for the flight (E-Ticket) or Santi Overseas will make necessary arrangement for flight ticket and departure.',
              'recuitment46': '12. Reception from Employer: ',
              'recuitment47': 'After the flight is confirmed we send flight details to our employer. Representative from employer will receive the candidates from airport and arrange hostel for them. Employer will provide the respective job duties to the candidates as per the employment agreement.',              
          'question1': 'What is free visa and free ticket program?',
          'question2': 'Is this truly the ZERO cost program?',
          'question3': 'What does this ZERO cost include?',
          'question4':
              'Will the company deduct all these above mentioned costs from the salary?',
          'answer1':
              'It is the visa system sanctioned by the employer bearing all the processing cost of the employees.',
          'answer2': 'Of course, this is indeed the ZERO cost program.',
          'answer3':
              'ZERO cost / Free of cost includes the following entities:\nPassport cost NPR 5000.00\nTraveling, lodging and fooding cost for interview\nMedical cost\nVisa cost\nInsurance and welfare cost\nOne-way travel cost to Kathmandu for flight\nTicket cost',
          'answer4':
              'Sorry, no cost shall be deducted since this is free of cost program.',
          
          'logOut': 'LogOut',
          //testimonials
          "testimonial1":"I am really indebted for being the part of Santi with the instrumental role. It is great to share my feeling about working from day 1 here. Santi has been a platform for the employees, the job-seekers and the foreign clients to exercise their potential to the career and the business goal as well. It is truly a one stop business solution partner as we deal with every foreign employment related issues through fast track. I don’t hesitate to state that Santi is scaling the apex in recruiting the workers for multinational companies as we are practicing RBA.In the nutshell, Santi Overseas Pvt. Ltd. has been the best choice of those individuals who are seeking jobs in foreign countries, and of those foreign clients who want to hire the elegant workforce to meet the business goal. The team is committed to give the best services through the veterans. Thank you!",
          "speaker1":"Surendra Rana",
          "testimonial2":"Ladies and Gentlemen !Let me share my sheer joy to be a part of this global forum of RBA via Santi Overseas Pvt. Ltd. Working with the team of veterans in the field of foreign employment has molded me much more in my performance. I am very privileged as the Program Co-ordinator, and striving for 100% to place Santi at the top among those who have had their own glorious history in this supply chain. Since we are a service oriented ethical agency, our primary focus goes on recruitment and deployment of an elegant work force to the employing company. We are truly committed to comply with the RBA COC  and the accessories during the total ethical practice. Ladies and gentlemen, ethically fair or transparent business is our commitment through the compliance of all the aspects of RBA Code of Conducts. We are proud of being involved, a brick of an esteemed castle, hoping to make this forum as the landmark. Hence, I would like to request all the members to unite for the promotion of all manufacturing and service  sectors holistically. Thank you !    ",
          "speaker2":"Rishi Ram Kapri",
          "testimonial3":"Dear valued clients,\nGreetings!\nWe take immense pleasure in introducing SANTI OVERSEAS PVT. LTD. as an ethical Human Resource recruitment agency based in the capital city of Nepal, Kathmandu. We are duly licensed by the Government of Nepal under the Department of Foreign Employment act with License No. 1495/074/075.\nGlobalization has made many things possible to have easy access to different resources from every nook and corner of this dynamic world. Moreover, forming a common platform with a global supply chain of goods and services has assisted the companies to accelerate the pace to meet the business goal. And, it is true to say that human resource is one of the strongest pillars for the sustainable growth of business. However, it has become the most critical decision a company has to make since it can be messed up. Keeping this in mind,  we lay great emphasis on the quality, attitude and skills of the personnel we offer to our clients ensuring timely, sound and cost-effective staffing.\nWe do assist our clients’ understanding in developing and implementing effective human resource recruiting and supplying programs and policies by working closely with them addressing their most important HR issues. We can source our clients with a wide range of personnel especially in the field of Industry, Security, Hospitality, Agriculture, Plantation, Sales & Marketing, Engineering, Construction, Corporate and IT sectors.\nThe company has aimed to give a complete HR solutions & support service to our valued clients to take the fullest advantage of our professional services that we offer. We have been closely associated with the development in our every endeavor to fulfill the employers’ as well as employees’ interests with our main concern for their full satisfaction.\nOur clients’ enquiry about HR solutions shall be nourished with the greatest care and we fully assure that our experienced team which is professionally trained and have already sourced a vast range of workforce to Malaysia and many other countries in the Middle East is committed in providing with the best quality services all the times.\nFinally, we are glad to be the part of an esteemed global forum, Responsible Business Alliance, and are committed to comply with the Code of Conduct hoping for a long-term mutually beneficial relationship in business. Thank you!",
       "speaker3":"Desk of the Chairman",
       "testimonial4":"Mr. Manu Kumar Lama is an accomplished and self-driven professional with an entrepreneurial unmatched spirit. Having a rich experience in the human resource management industry both in Nepal and Malaysia, Mr. Lama carries the overall responsibilities for the recruitment policies. For his excellent managerial skills and  knowledge, he strives for highly potential candidates nurturing them ethically to instill enthusiasm. The feedback from the thousands of candidates deployed to Malaysia, UAE, Saudi Arabia, Qatar and Oman along with the employers have proved his leadership and professionalism  in this business. The quality of dealing with the difficulties tactfully and critically has led him to the apex to build up a huge network in this field. His outstanding knowledge on Malay language both written and spoken has added a great asset in him establishing the relation of brotherhood among many big companies and people as well.\nMr. Manu Kumar Lama, being the member of different social organizations, has been involved in many social welfare and volunteer activities. His charitable attribute is reflected in the companies he is involved advocating different facilities to the staffs and those who go for foreign employment. He has played an instrumental role in SANTI to guild the business with ZERO COST policy to address the G2G agreement held between the Malaysian government and the government of Nepal, and in accordance with the RBA Code of Conduct. The Board of Directors are  proud of  the veteran Mr. MK Lama, the founder member and the Managing Director, wishing him all the best for his further success in this realm.",
      "speaker4":"MANAGING DIRECTOR'S",
        },
        'ne_NE': {
          'job': 'काम',
          'companies': 'कम्पनीहरु',
          'aboutUs': 'हाम्रो बारेमा',
          'login/signup': 'दर्ता गर्नुहोस',
          'forEmployees': 'रोजगारीका लागि',
          'Find the best work at foreign employment through SANTI OVERSEAS.':
              'शान्ति ओभरसिजको माध्यमबाट बैदेशिक रोजगारीमा उत्कृष्ट काम पाउनुहोस ।',
          'Fill up your profile to get your dream job.':
              'आफ्नो जानाकारी भर्नुहोस् र खोजेको जस्तो काम पाउनुहोस् ।',
          'santiOverseas': 'शान्ति\nओभरसिज ',
          "New Job": "नयाँ अवसर",
          'News': 'समाचारहरु',
          'FAQs': 'धेरै सोधिने प्रश्नहरु',
          "Testimonials": 'प्रमाणपत्रहरु',
          'companyInfo': "कम्पनी परिचय",
          'companyInfo1':
              "➼  शान्ति ओभरसिज प्रा. लि. नेपाल सरकारको कम्पनी ऐन अन्तर्गत दर्ता न.ं१७६८४७÷०७४÷०७५ र वैदेशिक रोजगार विभागबाट न.ं १४९५÷०७४÷०७५ को लाइसेन्स प्राप्त न्यानपावरको क्षेत्रमा लामो अनुभव हासिल गर्नुभएको दक्ष समुहद्वारा स्थापित एक अग्रणी संस्था हो । आप्mनो स्थापनाको छोटो समयमा नै विभिन्न देशका ठूला र नाम चलेका कम्पनीहरुमा सीप र क्षमताको आधारमा आकर्षक तलब सुविधाका साथ थुप्रै कामदारहरुलाई पठाउन सफल यस कम्पनी आज स्वदेश तथा विदेशमा एक प्रतिष्ठित र सुपरिचित नाम बन्न पुगेको छ ।\n\n ➼  शान्ति ओभरसिज प्रा. लि.का सञ्चालक तथा व्यवस्थापकहरुले म्यानपावरको क्षेत्रमा हासिल गर्नुभएको  लामो अनुभव एवं फराकिलो सञ्जालको माध्यमबाट मलेसिया लगायत खाडीक्षेत्रका विभिन्न देशहरुमा दक्ष, अर्ध–दक्ष र अदक्ष कामदारहरुलाई आकर्षक सेवा सुविधामा पठाई उनीहरुको आर्थिक, सामाजिक र वृत्ति विकासमा अतुलनिय योगदान पुर्याउन सफल यस संस्था हामीलाई विश्वास गरी आप्mनो कम्पनीलाई आवश्यक पर्ने योग्य कामदारहरु हाम्रो यस संस्था मार्फत माग गर्ने सम्पूर्ण रोजगारदाता कम्पनीहरुलाई आप्mनो उच्च व्यवसायिक दक्षताको प्रयोग गरी व्यवसायिक नैतिकताको दायराभित्र रहेर विगत, बर्तमान र भविष्यमा पनि न्युन लगानी र प्रयासमा उच्च सन्तुष्टि र सेवा प्रदान गर्दै आइरहेका छन् ।\n\n ➼  “म्यानपावर व्यवसाय भनेको साझेदारी र दीगो सम्वन्धको पुल हो”े भन्ने दर्शनबाट निर्देशित यस  शान्ति ओभरसिज प्रा. लि. को आप्mनो यही दर्शनको कारण आप्mना बर्षौ पहिलेका रोजगारदाता कम्पनीहरुसँगको सम्बन्ध आजभन्दा भोलि झन प्रगाढ हुँदै गइरहेको बर्तमान परिप्रेक्षमा हामी यही आदर्श र दर्शनलाई अँगाल्दै उच्च गुणस्तरको सेवा दिन वा छनौट कार्य गर्न प्रतिवद्ध छौँ । आप्mनो पेशागत दक्षता, अखण्डता, समयसापेक्ष प्रतिस्पर्धा, एकअर्का प्रतिको विश्वास, गुणस्तरिय सेवाबाट प्राप्त हुने सन्तुष्टि आदिका माध्यमबाट ग्राहकहरुको अपेक्षालाई सम्बोधन गर्न जुझारुकताका साथ सधैं अग्रसर रहनु यस संस्थाको एक प्रमुख उदेश्य रहन आउँछ । यिनै गुण र विशेषताका कारण शान्ति ओभरसिज प्रा. लि.विश्वविख्यात कम्पनीहरुका लागि कामदारहरु छनौट गरी पठाउने विश्वासिलो संस्थाको रुपमा सबैको रोजाइमा पर्न सफल भएको छ ।",
          'vision': 'हाम्रो भिजन',
          'vision1':
              '➼  विश्वभरि उच्च गुणस्तरका कर्मचारीहरु पूर्ति गरी आफुलाई एक गुणस्तरिय अवसर प्रदान गर्ने केन्द्रको रुपमा स्थापित गर्नु ।',
          'mission': 'हाम्रो मिसन',
          'mission1':
              '➼  कानुनको पालना गर्दै आप्mना ग्राहकहरुलाई फरक र विशेष प्रकारको सेवा प्रदान गर्ने ।',
          'mission2':
              '➼  उपलब्ध स्रोत र साधनको उच्चतम प्रयोग गर्दै हाम्रा निवेदक र ग्राहकहरुको इच्छा र आकाँक्षलाई सम्वोधन गर्ने ।',
          'mission3':
              '➼  नेपालको म्यानपावर व्यवसायको क्षेत्रमा गुणस्तरिय व्यवस्थापन अवलम्बन गर्ने एक अग्रणी संस्थाको रुपमा स्थापित गर्ने । ',
          'focus': 'हाम्रो प्राथमिकता ',
          'focus1':
              '➼  रोजगार प्रदायक कम्पनीहरु र कामदारहरुका बिचमा उच्चकोटीको स्रोतपुर्ण र गतिशिल अवसरहरु आदान प्रदान गर्ने ।',
          'focus2':
              '➼  प्रष्टरुपले परिभाषित प्रणाली, प्रक्रिया र रणनीतिक योजनाका साथ विश्वले नै अपनाउदै आएको ठाउँको ठाउँ समस्याको समाधान गर्ने ।',
          'focus3':
              '➼  नीतिगत व्यवस्थालाई कडाइका साथ पालना गर्दै माग अनुसार उपयुक्त व्यक्तिहरुको भर्ना र छनौटमा भरपुर सहयोग प्रदान गर्ने ।',
          'focus4':
              '➼  इन्जिनियरिङ्ग, निर्माण, उत्पादन, सुरक्षा, अतिथि सत्कार, मेनटेन्यान्स तथा अन्य सेवामुलक र नेतृत्वदायी क्षेत्रहरुलाई पूर्णरुपले समेट्ने ।',
          'focus5':
              '➼  शैक्षिक सचेतनाको माध्यमबाट वैदेशिक रोजगारीमा जाने कामदारहरुलाई प्रत्यक्षरुपले सहभागी  गराई उनीहरुको सशक्तिकरणको लागि सहयोग र समर्थन गर्ने ।',
          'question1': 'फ्रि भिसा, फ्रि टिकट कार्यक्रम भन्नाले के बुझिन्छ ?',
          'question2':
              'के यो वास्तवमा शुन्य लागत अर्थात पूर्ण निशुल्क को कार्यक्रम नै हो त?',
          'question3':
              'शुन्य लागत अर्थात पूर्ण निशुल्क भित्र कुन कुन सेवाहरु पर्दछन्?',
          'question4':
              'के यी माथि उल्लेखित खर्चहरु कम्पनिले कामदारहरुको तलबबाट कटाउनेछ?',
          'answer1':
              'रोजगारदाताले आफ्नो कम्पनिमा काम गर्न आउन चाहने कामदारहरुलाई उक्त प्रक्रियाको लागि आवश्यक पर्ने सम्पूर्ण खर्च बेहोर्ने गरी लागु गरिएको भिसा प्रणाली हो भन्ने बुझिन्छ ।',
          'answer2':
              'अवश्य, यो कार्यक्रम वास्तवमै शुन्य लागत अर्थात पूर्ण निशुल्क को कार्यक्रम हो ।',
          'answer3':
              'शुन्य लागत अर्थात पूर्ण निशुल्क भित्र निम्नानुसारका सेवाहरु पर्दछन्:\nराहदानी खर्च ने.रु. ५०००।– \nअन्तरवार्ताको लागि आउँदा लाग्ने यातायात, बस्ने र खाने खर्च\nमेडिकल गर्ने खर्च\nभिषाको लागि लाग्ने खर्च\nबिमा तथा अन्य कल्याणकारी खर्च\nहवाई को समयमा घरदेखि काठमाडौं सम्मको यातायात खर्च\nविदेशजाने हवाई टिकट',
          'answer4':
              'के यी माथि उल्लेखित खर्चहरु कम्पनिले कामदारहरुको तलबबाट कटाउनेछ?माफ गर्नुहोला, जब यो कार्यक्रम नै निशुल्क भन्ने छ, खर्च कटाउने त प्रश्नै उठ्दैन नी, धन्यवाद ।, ',
          'logOut': 'LogOut',
           'cooperate':'CORPORATE VALUES',
              'cooperate1':'To demonstrate our steadfast commitment to: ',
              'cooperate2':'Leadership: We will be a leader in every aspect of our business and in development of our team. Leadership skills in our performance is the way we manage, design, build and support our products. ',
              'cooperate3': 'Customer satisfaction: Our success depends upon the satisfaction of our    customers, and that is to be achieved through the total understanding of what they actually want, and delivering it flawlessly. ',
              'cooperate4': 'Integrity: We practice the highest ethical standards by honoring our commitments. ',
              'cooperate5': 'Quality: We strive for continuous quality    improvement in all that we do. ',
            'recruit': 'WHY  TO RECRUIT NEPALESE WORKERS?',
            'recruit1': 'Through the experience gained over the year in the foreign employment, it has been seen that many countries have shown their interest in hiring the Nepalese professional, skilled, semi-skilled and unskilled manpower because of the following reasons :',
            'recruit2': '➼ We are always between clients and candidates to assure that recruitment process runs quickly and smoothly and inform them about the progress in every step',
            'recruit3': '➼ We have developed a web and mobile app to facilitate the enrollment of nepali worker. ',
            'recruit4': '➼ We help you to get the best candidates and best jobs. ',
            'recruit5': '➼ We provide services through our team of highly professional and trained recruitment consultants. ',
            'recruit6': '➼ We are very cost effective without compromising with the quality. ',
            'recruit7': '➼ We focus on individual approach to our clients and candidates to understand their requirements and special needs to achieve quality results.',
            'recruit8': '➼ We are known for deployment of quality and reliable manpower on time according to employer\'s convenience ',
            'recruit9': '➼ We are responsive as well as communicative, so we do not let any gaps in between the client and us. We are transparent and make the recruitment process as simple as possible.',
            'recruit10': '➼ We are affiliated with top Training Institute and we can provide refreshment training and full training as well to the applicant whenever they require. ',
            'terms':'RECRUITMENT TERMS AND CONDITIONS',
            'terms1':'1. The FIRST PARTY shall issue the Demand letter to the SECOND PARTY mentioning the number of workers required and their categories, rate of salary and other service conditions of workers, along with Power of Attorney, Guarantee Letter, Manpower Recruitment Agreement and Employment Contract (authorizing the SECOND PARTY) to recruit and expatriate the worker from Nepal on behalf of the FIRST PARTY. Demand Letter and Power of Attorney should be attested by the Chambers of Commerce of employing country, Foreign Ministry and Nepal Embassy. ',
            'terms2':'2. Both parties herein shall obtain the approval of the respective government to import, recruit and supply the workers as per the rules and regulation of both countries in regard to the condition necessary to import and supply. ',
            'terms3':'3. The SECOND PARTY shall be responsible for short-listing of qualified candidates according to their trade qualifications and experience in conformity with the FIRST PARTY\'S requirements. The SECOND PARTY should notify the FIRST PARTY of such short listed qualified candidates who are ready for final Interview and selection. ',
            'terms4':'4. The FIRST PARTY has the right to either send his representative or give the SECOND PARTY the right to select process and send such qualified workers at the SECOND PARTY\'S full guarantee. ',
            'terms5':'5. The worker will be interviewed, tested and selected by representative of the employer or by SECOND PARTY on his behalf. The FIRST PARTY agrees to advise to the SECOND PARTY of its final list personnel selected through fax, email or letter and the desired mobilization date on the respective site. ',
            'terms6':'6. The SECOND PARTY shall assist the workers in matters related to Nepal immigration and government formalities, medical tests and Visa stamping along with all other relevant approvals from the embassy of the country concerned. ',
            'terms7':'7. The SECOND PARTY shall, at his own expenses, provide airport assistance to the departing workers and inform the FIRST PARTY of their arrival detail by any means of communication (Fax, Email or Telephone) so as to receive them on arrival. ',
            'terms8':'8. The FIRST PARTY will pay all the expenses to bring the candidates to Malaysia. ',
            'terms9':'9. The FIRST PARTY will be responsible for receiving the workers at the airport in part and as whole as per requirement of the client and validity of Visa of the concerned country. ',
            'terms10':'10. The earning of the worker per month and other service conditions shall be as per the attached demand letter and contract document against each category. The FIRST PARTY should clearly inform the SECOND PARTY about the salary and any other deduction as Tax etc being paid by the employer and SECOND PARTY in turn should clearly inform the candidate accordingly. ',
            'terms11': '11. Within the three (3) month probation period from the commencement of employment, if the employer finds the selected worker to be unfit, unqualified to continue the employment, refuse to work, failed the medical tests upon arrival to destination country or considered as a security threat, the EMPLOYER may replace the worker. The replacement of the unqualified worker shall be done by the SECOND PARTY at maximum of a month from the termination of the unqualified worker. All expenses incurred, in relation there to, shall be borne by the SECOND PARTY. ',
            'terms12': '12. Arrival of the selected candidates will be within One Month upon issuing their visas. For any delay rather than this period, the visas will be cancelled and the SECOND PARTY will shoulder all the governmental expenses for replacement. ',
            'terms13': '13. FIRST PARTY has to compensate the candidate on their own expenditure if  the candidate will not get all facilities as per Employment Contract, and the  company will collapse before contract periods. ',
            'terms14': '14. The FIRST PARTY agrees to bear the compensation in case of death or injury of the workers and also agrees to bear the cost of transport of dead body to Nepal as per the labor law of country concerned. ',
              'recuitment': 'RECRUITMENT PROCEDURES',
              'recuitment1': '1. Initial Enquiry from employer: ',
              'recuitment2': 'The employer may contact recruitment companies directly and discuss your specific requirement and details on terms and conditions of service for Nepali workers. ',
              'recuitment3': '2. Legal Documents from employer for government formalities. ',
              'recuitment4': 'Once requirement is confirmed and initial agreement is made between recruitment companies (Nepal) and employer regarding terms and conditions and selection process, the employing company requires to produce the following duly authenticated/ attested documents in favor of recruitment companies (Nepal) to finalize the recruiting process as per Nepalese Government labor law: ',
              'recuitment5': '1. Power of Attorney between Recruiting Agent and Employer. ',
              'recuitment6': '2. Demand Letter listing the manpower requirement and terms and conditions. ',
              'recuitment7': '3. Employment Contract including terms and conditions of service. ',
              'recuitment8': '4. Recruitment Service Agreement listing each party responsibility. ',
              'recuitment9': '5. Guarantee letter confirming country of employment. ',
              'recuitment10': 'Once the above mentioned original documents are received from employer, recruitment companies will submit application to Department of Labor for authorization. ',
              'recuitment11': '2. Pre-Labour Approval: ',
              'recuitment12': 'After receiving the authorized demand letter from the company, the document are presented for pre- labor approval. The department of Labor in Nepal analyzes the document and approve for further processing. ',
              'recuitment13': '3. Manpower Pooling: Advertisement, Screening and short listing. ',
              'recuitment14': 'Once the Department of Labor is satisfied about the credibility of the demand, attestation and terms and conditions offered are conformity with the government regulation, the Government grants the permission to recruiting agency for advertise the requirement in local and national newspapers and start of recruitment process. Recruitment Company starts screening and short listing candidates before final interview. The process includes: ',
              'recuitment15': '1. Print and Broadcast Media Advertisement ',
              'recuitment16': '2. On-the-spot-sourcing (City and Provincial) ',
              'recuitment17': '3. Through Our Highly Qualified Agents ',
              'recuitment18': '4. Recommended Personnel ',
              'recuitment19': '5. Internal Candidate Bank ',
              'recuitment20': '4. Selection: ',
              'recuitment21': 'The mode of selection of contract workers may be executed under the following procedures: ',
              'recuitment22': 'Preliminary Interview: ',
              'recuitment23': 'We maintain upto date data bank of potential candidates with full information on their skill and education, technical knowhow and experience as per the employer criterion. Santi Overseas will short list the candidate for pre-interview and determine the capabilities of each applicant via one-on-one interviews to ascertain who are most qualified and fit for the employer\'s final selection. ',
              'recuitment24': 'Final Interview/Selection: ',
              'recuitment25': 'Selection by Employer\'s Authorized Representative, Recruitment Company Personnel. ',
              'recuitment26': 'Direct Interview (by Employer): ',
              'recuitment27': '  Many employers visit Nepal for final interview. We make all necessary preparations for interview. We call short listed candidates for the particular day. ',
              'recuitment28': 'Interview on behalf of Employer: ',
              'recuitment29': 'Sometimes manpower importing agencies give full authority to manpower consultant for entire selection procedures. In such case, we carry out interviews on behalf of employers abroad and make all dispatching arrangements to the employment destination. The selection is made purely on merit basis and finally select the most competent workers from our manpower reserve. ',
              'recuitment30': 'Interview through Skype: ',
              'recuitment31': 'Sometimes manpower importing agencies  select the candidate through interview via online (Skype). We make all the necessary arrangements for this process. ',
              'recuitment32': 'Transmittal of Resumes: ',
              'recuitment33': 'Employer may select the candidates from the Resumé of all prospective candidates. We forward the resumés of the candidates who have passed the pre-qualification interview and testing conducted at our end. In such cases, the name of the successful candidates may be relayed to us via phone, fax, or email. ',
              'recuitment34': '5. Full Documentation Assistance: ',
              'recuitment35': 'We provide the selected applicants\' assistance in securing the travel documents required by both Labour Office and Embassy, like Trade Test, Passport, Police Clearance, Medical Certificate, Orientation and Exit Pass. ',
              'recuitment36': '6. Medical Checkup: ',
              'recuitment37': 'The selected candidates are sent to an authorized hospitals or clinics for a full medical examination (and vaccination if required). The candidates who are medically and physically fit for employment are forwarded for recruitment process such as contract signing, visa processing. ',
              'recuitment38': '7. Employment Visa Process: ',
              'recuitment39': 'Once selected candidates are medically and physically fit, employer has to process their employment visa. The Visa system varies country to country. For the country with paper visa system, employer has to make copy of issued visa available to recruitment companies as soon as visa is issued for individuals for government clearance for mobilization. But for the country where visa has to be endorsed onto a passport, employing company provides all necessary documents to assist visa endorsement from embassy of employing country. ',
              'recuitment40': '8. Orientation: ',
              'recuitment41': 'Nepal labor law requires all new candidates traveling overseas for employment take orientation class to familiarize local laws & orders, labor laws and immigration policy, environment and tradition and culture of employing country. Candidates should also understand their responsibilities, terms and conditions and benefits of employment prior to submitting for final approval for mobilization. ',
              'recuitment42': '9. Final Labour Approval: (Government Clearance) ',
              'recuitment43': 'All the necessary documents like original passport, visa copy (original if not issued online), medical report, orientation certificate, insurance policy are submitted in Labor Department of Nepal for final approval and immigration clearance. The Department of Labor analyzes the documents and provides final approval. ',
              'recuitment44': '11. Travel Arrangement: ',
              'recuitment45': 'Once paper visa is received or visa is endorsed from embassy of employing country, Employer may proceed for the flight (E-Ticket) or Santi Overseas will make necessary arrangement for flight ticket and departure.',
              'recuitment46': '12. Reception from Employer: ',
              'recuitment47': 'After the flight is confirmed we send flight details to our employer. Representative from employer will receive the candidates from airport and arrange hostel for them. Employer will provide the respective job duties to the candidates as per the employment agreement.',          
           //testimonials
          "testimonial1":"सान्तिको भूमिकामा भूमिका निर्वाह गरेकोमा म साँच्चै ऋणी छु। यहाँ दिन 1 देखि काम गर्ने बारे मेरो भावना साझा गर्न राम्रो छ। Santi कर्मचारी, जागिर खोज्ने र विदेशी ग्राहकहरु लाई आफ्नो करियर र व्यापार लक्ष्य को लागी आफ्नो क्षमता प्रयोग गर्न को लागी एक प्लेटफर्म भएको छ। यो साँच्चै एक स्टप व्यापार समाधान साझेदार हो किनकि हामी फास्ट ट्र्याक मार्फत हरेक वैदेशिक रोजगारी सम्बन्धी मुद्दाहरू समाधान गर्छौं। म यो बताउन हिचकिचाउँदिन कि सन्तीले बहुराष्ट्रिय कम्पनीका लागि कामदार भर्ती गर्न शीर्ष मापन गरिरहेको छ किनकि हामी आरबीए अभ्यास गरिरहेका छौं। संक्षेपमा, Santi Overseas Pvt. Ltd. विदेशी देशहरूमा रोजगारी खोजिरहेका व्यक्तिहरू र व्यापार लक्ष्य पूरा गर्न सुरुचिपूर्ण कार्यबललाई भर्ती गर्न चाहने विदेशी ग्राहकहरूका लागि उत्तम छनोट भएको छ। टोली दिग्गजहरू मार्फत उत्कृष्ट सेवाहरू दिन प्रतिबद्ध छ। धन्यवाद!",
          "speaker1":"सुरेन्द्र राणा",
          "testimonial2":"महिला तथा सज्जनबृन्द, शान्ति ओभरसिज प्रा.लि को माध्यमबाट RBA को यो ग्लोबल मन्चको एउटा सदस्य हुन पाएकोमा म यहाँहरु समक्ष मेरो गहिरो खुशि बाडन चाहन्छु l बैदेशिक रोजगार संग सम्वन्धित अनुभवी र दक्ष व्यक्ति हरुको समुहमा काम गर्दा म आफू पनि परिष्कृत हुदै कार्यक्रम संयोजकको रुपमा यस संस्थालाई एक गौरवशाली इतिहास कायम राख्दै बैदेशिक रोजगारीको क्षेत्रमा एक अग्रणी संस्थाको रुपमा स्थापित गर्न हरसम्भव प्रयासरत रहिअएका छौं l शान्ति ओभरसिज प्रा.लि. RBA को आचार संहिता भित्र रहेर बैदेशिक रोजगारीमा जान चाहने नेपाली युवाहरुलाई सम्पूर्ण रुपले शुन्य लागतमा प्रशिक्षण प्रदान गरी उनीहरुको दक्षता र सीप अनुसारको रोजगारी प्राप्त गर्न यस संस्थाको सम्पर्कमा रहेका विभिन्न देशका बहुराष्ट्रिय कम्पनीहरुमा आकर्षक सेवा सुविधाका साथ पठाउने एक सेवाप्रदायक सदस्य सस्था हो  l शुन्य लागत अन्तर्गत बैदेशिक रोजगारीमा जान चाहने प्रशिक्षार्थी कामदारहरुको पासपोर्ट बनाउने, घरदेखि काठमाडौ सम्म जाने यातायात खर्च, खाने बस्ने खर्च, फोटो खिच्ने र मेडिकल चेकअप खर्च, भिषा फी र हवाई टिकट, एयरपोर्ट सम्म जाने र अर्को देशको  एयरपोर्टमा पुगेपछि लिन आउने र होस्टेल सम्म पुर्याउने सम्मका सम्पूर्ण खर्च पर्दछ अर्थात्   प्रशिक्षार्थी कामदारहरुले यी माथि उल्लेखित कुनैपनि खर्च तिर्नुपर्ने छैन l तसर्थ: शान्ति ओभरसिज को तर्फबाट बैदेशिक रोजगारीमा जान चाहने सम्पूर्ण युवाहरुलाई  बैदेशिक रोजगारी सम्वन्धी कुनै समस्या तथा जिज्ञासा रहेमा कुनै एजेन्ट बिनानै हामीलाई सम्पर्क गर्नुहुन अनुरोध गर्दछौ l एजेन्टहरुको लहैलहैमा लागेर  आफ्नो पैसा नफसाउनु हुन पनि हामी सचेत गराउदछौ l  ",
          "speaker2":"ऋषिराम काप्री",
          "testimonial3":"यहाँहरु सबैमा नमस्कार, नेपाल सरकारको वैदेशिक रोजगार विभागबाट लाइसेन्स नम्बर १४९५/०७४/०७५ प्राप्त काठमाडौं महानगरपालिका वडा न. ४, महाराजगन्ज चुनदेवीमा अवस्थित शान्ति ओभरसिज प्रा.लि को अध्यक्ष को तर्फबाट यहाँहरु सबैलाई नमस्कार गर्दै यस संस्थामा स्वागत गर्न चाहन्छु l  \nभूमण्डलीकरणले गतिशील आजको विश्वको कुना कन्दरामा पनि मानिसको पहुचलाई सजिलो बनाएको आजको अवस्थामा विश्वको विभिन्न ठाउँमा उपलब्ध बस्तु तथा सेवा वितरणलाई पनि फराकिलो बनाएको कुरा सबैमा विदितै छ l यहि कुरालाई मध्यनजर गर्दै नेपाल सरकारले सम्झौता गरे अनुरुपका देशहरुका ठूला र बहुराष्ट्रिय उत्पादनमुलक कम्पनीहरुलाई आवश्यक पर्ने मानव संसाधन प्रचलित कानूनको बर्खिलाप नहुने र सम्पूर्णरुपले कानूनी मापदण्ड पूरागरी पूर्ति गर्ने उद्देश्यका साथ शान्ति ओभरसिज प्रा.लि. ले RBA जस्तो अन्तर्राष्ट्रिय मंचको सदस्यता लिएर शुन्य लागतमा सम्पूर्णरूपले जाने देश, कम्पनी, कामको प्रकृति र सेवा सुविधा आदिको बारेमा प्रशिक्षण दिई इच्छुक व्यक्तिहरुलाई बैदेशिक रोजगारीमा पठाउदछ l \nयसरी वैदेशिक रोजगारीका लागि पठाउने कामदारहरुको छनौट गर्दा शान्ति ओभरसिज प्रा.लि. ले जहिले पनि रोजगारदाता कम्पनीहरुले तोकेको मापदण्डलाई प्राथमिकतामा राख्दै ………… ",
       "speaker3":"Desk of the Chairman",
       "testimonial4":" यस शान्ति ओभरसिज प्रा.लि. का प्रबन्ध निर्देशक श्री मनु कुमार लामा बैदेशिक रोजगारीको क्षेत्रमा एक सु-परिचित नाम हो l विशेषत: नेपाल र मलेशियाका सरकारहरुको बिचमा भएको श्रम सम्झौता सम्बन्धि जानकार र मलाया भाषाका विज्ञ हुनुले पनि मलेशियाका दर्जनौ ठूला बहुराष्ट्रिय कम्पनीहरु संगको बर्षौ देखिको उहाँको सहकार्य आफैमा एक गौरवशाली सफलता बनेको छ l यस्तो परिप्रेक्षमा उहाँले नेतृत्व प्रदान गर्नुभएको यस शान्ति ओभरसिज प्रा.लि. आज बैदेशिक रोजगारीको क्षेत्रमा एक अग्रणी संस्थाको रुपमा स्थापित भएको कुरा सबैमा विदितै छ l ",
      "speaker4":"MANAGING DIRECTOR'S",
        }
      };
}
